-- MySQL Script generated by MySQL Workbench
-- Tue May 16 17:53:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema otk
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema otk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `otk` DEFAULT CHARACTER SET utf8 ;
USE `otk` ;

-- -----------------------------------------------------
-- Table `otk`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `otk`.`roles` (
  `code` VARCHAR(50) NOT NULL,
  `description` VARCHAR(250) NOT NULL,
  `employee` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `otk`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `otk`.`customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL,
  `address` VARCHAR(250) NOT NULL,
  `phone` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `otk`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `otk`.`users` (
  `login` VARCHAR(50) NOT NULL,
  `customerId` INT NOT NULL,
  `roleCode` VARCHAR(50) NOT NULL,
  `name` VARCHAR(250) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`login`),
  INDEX `fk_customers_idx` (`customerId` ASC) VISIBLE,
  INDEX `fk_roles_idx` (`roleCode` ASC) VISIBLE,
  CONSTRAINT `fk_customers`
    FOREIGN KEY (`customerId`)
    REFERENCES `otk`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_roles`
    FOREIGN KEY (`roleCode`)
    REFERENCES `otk`.`roles` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `otk`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `otk`.`services` (
  `id` INT NOT NULL,
  `name` VARCHAR(250) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `otk`.`statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `otk`.`statuses` (
  `status` VARCHAR(50) NOT NULL,
  `description` VARCHAR(250) NOT NULL,
  `level` INT NULL DEFAULT 100,
  PRIMARY KEY (`status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `otk`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `otk`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userLogin` VARCHAR(50) NOT NULL,
  `serviceId` INT NOT NULL,
  `discountPercent` DECIMAL(10,2) NULL,
  `status` VARCHAR(50) NOT NULL DEFAULT 'Новый',
  PRIMARY KEY (`id`),
  INDEX `fk_users_idx` (`userLogin` ASC) VISIBLE,
  INDEX `fk_services_idx` (`serviceId` ASC) VISIBLE,
  INDEX `fk_statuses_idx` (`status` ASC) VISIBLE,
  CONSTRAINT `fk_users`
    FOREIGN KEY (`userLogin`)
    REFERENCES `otk`.`users` (`login`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_services`
    FOREIGN KEY (`serviceId`)
    REFERENCES `otk`.`services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_statuses`
    FOREIGN KEY (`status`)
    REFERENCES `otk`.`statuses` (`status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `otk`.`orders_arch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `otk`.`orders_arch` (
  `id` INT NOT NULL,
  `userLogin` VARCHAR(50) NOT NULL,
  `serviceId` INT NOT NULL,
  `discountPercent` DECIMAL(10,2) NULL,
  `status` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_idx` (`userLogin` ASC) VISIBLE,
  INDEX `fk_services_idx` (`serviceId` ASC) VISIBLE,
  INDEX `fk_statuses_idx` (`status` ASC) VISIBLE,
  CONSTRAINT `fk_users_arch`
    FOREIGN KEY (`userLogin`)
    REFERENCES `otk`.`users` (`login`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_services_arch`
    FOREIGN KEY (`serviceId`)
    REFERENCES `otk`.`services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_statuses_arch`
    FOREIGN KEY (`status`)
    REFERENCES `otk`.`statuses` (`status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `otk`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `otk`.`category` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`));


-- -----------------------------------------------------
-- Table `otk`.`category_1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `otk`.`category_1` (
  `id INT` INT NOT NULL,
  ` name VARCHAR(250)` VARCHAR(255) NOT NULL,
  `address Varchar(250)` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id INT`));


-- -----------------------------------------------------
-- Table `otk`.`category_2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `otk`.`category_2` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `level int` VARCHAR(45) NULL,
  `category_1_id INT` INT NOT NULL,
  PRIMARY KEY (`category_id`),
  INDEX `fk_category_2_category_11_idx` (`category_1_id INT` ASC) VISIBLE,
  CONSTRAINT `fk_category_2_category_11`
    FOREIGN KEY (`category_1_id INT`)
    REFERENCES `otk`.`category_1` (`id INT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
